### ISSUE TITLE
Remove related content overlap in print styles

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#307] opened 2015-10-29 12:53 UTC
Review print output on the main content types and adjust spacing and overlap, such as the related content module.

<img width="563" alt="print-results" src="https://cloud.githubusercontent.com/assets/7241111/10818727/3697b200-7e1a-11e5-8eef-35e3bab1fe7e.png">

**Comment by murtaugh** [comment] 2015-10-29 14:58
CLosing as dupe of #305

**Closed by murtaugh** 2015-10-29 14:58 UTC
Labels: minor bug
