### ISSUE TITLE
Reported ad issue on mobile

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#369] opened 2016-04-11 22:42 UTC
An author looking at the site on android+latest Chrome says the Event Apart ad is broken on all pages he visited (and thinks the text was just too long)

**Comment by michellekondou** [comment] 2016-04-12 09:33
This I can't reproduce, is anyone else seeing this?

**Comment by m1ca** [comment] 2016-04-12 14:15
@michellekondou no, I have't been able to

**Comment by michellekondou** [comment] 2016-04-14 13:31
@m1ca @murtaugh Since we haven't been to reporduce this I'm closing the issue!

**Closed by michellekondou** 2016-04-14 13:31 UTC
